name: sensor.feedsparser
description: 📰 RSS feeds custom component for Home Assistant
type: component
keywords:
  - sensor
  - feedsparser
  - rss
  - feed
  - list
author:
  name: ad
  homepage: https://github.com/ad/feedsparser
license: MIT
files:
  - custom_components/feedsparser/sensor.py
  - custom_components/feedsparser/manifest.json
