name: sensor.feedparser
description: 📰 RSS feed custom component for Home Assistant
type: component
keywords:
  - sensor
  - feedparser
  - rss
  - feed
  - list
author:
  name: ad
  homepage: https://github.com/ad/feedparser
license: MIT
files:
  - custom_components/feedparser/sensor.py
  - custom_components/feedparser/manifest.json
